Saving income.csv to income.csv

{'income.csv': b'id,age,income,occupation,years of experience\r\n1,64,35397,developer,10\r\n2,54,32943,teacher,3\r\n3,43,21947,professor,9\r\n4,21,37092,engineer,5\r\n5,64,35935,accountant,10\r\n6,52,38933,mechanic,1\r\n7,37,22040,electrician,8\r\n8,37,36656,software engineer,5\r\n9,43,32220,tester,13\r\n10,26,36691,designer,3\r\n11,32,32283,developer,0\r\n12,40,27773,teacher,1\r\n13,43,30195,professor,5\r\n14,36,23926,engineer,0\r\n15,59,39369,accountant,10\r\n16,53,28486,mechanic,10\r\n17,65,37904,electrician,20\r\n18,20,32601,software engineer,19\r\n19,62,20494,tester,1\r\n20,58,35202,designer,9\r\n21,50,23974,developer,11\r\n22,39,21239,teacher,20\r\n23,34,23712,professor,18\r\n24,62,27435,engineer,13\r\n25,26,29457,accountant,19\r\n26,27,33222,mechanic,8\r\n27,33,29918,electrician,7\r\n28,43,37929,software engineer,17\r\n29,46,21063,tester,12\r\n30,37,28859,designer,6\r\n31,38,28751,developer,14\r\n32,47,25256,teacher,14\r\n33,51,30667,professor,2\r\n34,24,37021,engineer,7\r\n35,58,26798,accountant,9\r\n36,64,20465,mechanic,14\r\n37,53,37197,electrician,11\r\n38,26,35320,software engineer,7\r\n39,47,21012,tester,15\r\n40,45,26067,designer,20\r\n41,36,38519,developer,15\r\n42,40,22165,teacher,1\r\n43,45,36675,professor,2\r\n44,30,26865,engineer,11\r\n45,44,34992,accountant,12\r\n46,20,21214,mechanic,11\r\n47,54,26332,electrician,3\r\n48,57,20762,software engineer,1\r\n49,46,25015,tester,4\r\n50,26,23520,designer,15\r\n51,37,31716,developer,0\r\n52,57,31347,teacher,1\r\n53,40,25089,professor,10\r\n54,20,39122,engineer,13\r\n55,34,39371,accountant,16\r\n56,25,24785,mechanic,2\r\n57,32,26542,electrician,9\r\n58,41,32278,software engineer,5\r\n59,52,34374,tester,1\r\n60,44,27391,designer,19\r\n61,55,32322,developer,20\r\n62,60,36866,teacher,10\r\n63,23,30692,professor,7\r\n64,43,31789,engineer,15\r\n65,30,39148,accountant,17\r\n66,36,21191,mechanic,19\r\n67,30,31950,electrician,16\r\n68,61,31861,software engineer,10\r\n69,46,22332,tester,16\r\n70,37,39543,designer,15\r\n71,42,25617,developer,2\r\n72,28,22100,teacher,17\r\n73,63,38487,professor,1\r\n74,54,34357,engineer,14\r\n75,29,29091,accountant,7\r\n76,36,37788,mechanic,18\r\n77,45,26830,electrician,3\r\n78,41,35312,software engineer,20\r\n79,30,38864,tester,10\r\n80,32,32462,designer,8\r\n81,59,30955,developer,3\r\n82,33,32195,teacher,7\r\n83,35,33452,professor,11\r\n84,40,23181,engineer,17\r\n85,58,32204,accountant,17\r\n86,65,27389,mechanic,3\r\n87,37,34208,electrician,16\r\n88,35,38912,software engineer,0\r\n89,57,30736,tester,20\r\n90,55,20472,designer,2\r\n91,39,28007,developer,10\r\n92,29,30789,teacher,11\r\n93,23,28714,professor,8\r\n94,29,39385,engineer,14\r\n95,24,30714,accountant,6\r\n96,25,20576,mechanic,10\r\n97,26,21664,electrician,16\r\n98,55,20861,software engineer,8\r\n99,46,34936,tester,18\r\n100,31,33452,designer,2\r\n101,54,27633,developer,2\r\n'}

In [5]:
# Load the CSV file
file_path = "income.csv"  # Change this to your actual file path
df = pd.read_csv(file_path)

# Display first few rows of the dataset
print("Sample Dataset:\n", df.head())

Sample Dataset:
    id  age  income  occupation  years of experience
0   1   64   35397   developer                   10
1   2   54   32943     teacher                    3
2   3   43   21947   professor                    9
3   4   21   37092    engineer                    5
4   5   64   35935  accountant                   10

In [6]:
df.tail()

      id  age  income         occupation  years of experience
96    97   26   21664        electrician                   16
97    98   55   20861  software engineer                    8
98    99   46   34936             tester                   18
99   100   31   33452           designer                    2
100  101   54   27633          developer                    2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   101 non-null    int64
 1   age                  101 non-null    int64
 2   income               101 non-null    int64
 3   occupation           101 non-null    object
 4   years of experience  101 non-null    int64
dtypes: int64(4), object(1)
memory usage: 4.1+ KB

In [8]:
df.describe(include="all")

                id         age        income occupation  years of experience
count   101.000000  101.000000    101.000000        101           101.000000
unique         NaN         NaN           NaN         10                  NaN
top            NaN         NaN           NaN  developer                  NaN
freq           NaN         NaN           NaN         11                  NaN
mean     51.000000   41.732673  30203.564356        NaN             9.732673
std      29.300171   12.670352   5925.322711        NaN             6.177202
min       1.000000   20.000000  20465.000000        NaN             0.000000
25%      26.000000   32.000000  25256.000000        NaN             4.000000
50%      51.000000   40.000000  30736.000000        NaN            10.000000
75%      76.000000   53.000000  35202.000000        NaN            15.000000
max     101.000000   65.000000  39543.000000        NaN            20.000000

In [10]:
print(df.shape)
print(df.size)
print(df.ndim)
print(df.columns)

(101, 5)
505
2
Index(['id', 'age', 'income', 'occupation', 'years of experience'], dtype='object')

In [11]:
print(df.isnull())
print(df.isna())
print(df.isna().sum())

        id    age  income  occupation  years of experience
0    False  False   False       False                False
1    False  False   False       False                False
2    False  False   False       False                False
3    False  False   False       False                False
4    False  False   False       False                False
..     ...    ...     ...         ...                  ...
96   False  False   False       False                False
97   False  False   False       False                False
98   False  False   False       False                False
99   False  False   False       False                False
100  False  False   False       False                False

[101 rows x 5 columns]
        id    age  income  occupation  years of experience
0    False  False   False       False                False
1    False  False   False       False                False
2    False  False   False       False                False
3    False  False   False       False                False
4    False  False   False       False                False
..     ...    ...     ...         ...                  ...
96   False  False   False       False                False
97   False  False   False       False                False
98   False  False   False       False                False
99   False  False   False       False                False
100  False  False   False       False                False

[101 rows x 5 columns]
id                     0
age                    0
income                 0
occupation             0
years of experience    0
dtype: int64

In [13]:
categorical_col = "age"  # Change this to your categorical column
numerical_col = "income"  # Change this to your numerical column

# Check for missing values and fill them if necessary
df[numerical_col] = df[numerical_col].fillna(df[numerical_col].median())

# Compute summary statistics grouped by the categorical column
summary_stats = df.groupby(categorical_col)[numerical_col].agg(
    mean="mean",
    median="median",
    min="min",
    max="max",
    std="std"
)

# Create a list of grouped values
grouped_values = df.groupby(categorical_col)[numerical_col].apply(list)

# Display results
print("\nSummary Statistics:")
print(summary_stats)

print("\nGrouped Values as List:")
print(grouped_values)

# Save the results to CSV files
summary_stats.to_csv("summary_statistics.csv")
grouped_values.to_csv("grouped_values.csv")

print("\nSummary statistics saved to 'summary_statistics.csv'")
print("Grouped values saved to 'grouped_values.csv'")

Summary Statistics:
             mean   median    min    max           std
age
20   30979.000000  32601.0  21214  39122   9063.513612
21   37092.000000  37092.0  37092  37092           NaN
23   29703.000000  29703.0  28714  30692   1398.657213
24   33867.500000  33867.5  30714  37021   4459.722469
25   22680.500000  22680.5  20576  24785   2976.212442
26   29330.400000  29457.0  21664  36691   6756.556172
27   33222.000000  33222.0  33222  33222           NaN
28   22100.000000  22100.0  22100  22100           NaN
29   33088.333333  30789.0  29091  39385   5518.768824
30   34206.750000  35407.0  26865  39148   5918.900313
31   33452.000000  33452.0  33452  33452           NaN
32   30429.000000  32283.0  26542  32462   3367.430326
33   31056.500000  31056.5  29918  32195   1610.082141
34   31541.500000  31541.5  23712  39371  11072.585087
35   36182.000000  36182.0  33452  38912   3860.803025
36   30356.000000  30857.0  21191  38519   9077.652376
37   32170.333333  32962.0  22040  39543   6203.619997
38   28751.000000  28751.0  28751  28751           NaN
39   24623.000000  24623.0  21239  28007   4785.698695
40   24552.000000  24135.0  22165  27773   2465.807508
41   33795.000000  33795.0  32278  35312   2145.361974
42   25617.000000  25617.0  25617  25617           NaN
43   30816.000000  31789.0  21947  37929   5756.681249
44   31191.500000  31191.5  27391  34992   5374.718644
45   29857.333333  26830.0  26067  36675   5916.584854
46   25836.500000  23673.5  21063  34936   6286.058251
47   23134.000000  23134.0  21012  25256   3000.961179
50   23974.000000  23974.0  23974  23974           NaN
51   30667.000000  30667.0  30667  30667           NaN
52   36653.500000  36653.5  34374  38933   3223.699815
53   32841.500000  32841.5  28486  37197   6159.607171
54   30316.250000  30288.0  26332  34357   3928.594098
55   24551.666667  20861.0  20472  32322   6732.116334
57   27615.000000  30736.0  20762  31347   5942.729760
58   31401.333333  32204.0  26798  35202   4259.108984
59   35162.000000  35162.0  30955  39369   5949.596457
60   36866.000000  36866.0  36866  36866           NaN
61   31861.000000  31861.0  31861  31861           NaN
62   23964.500000  23964.5  20494  27435   4908.028168
63   38487.000000  38487.0  38487  38487           NaN
64   30599.000000  35397.0  20465  35935   8780.422997
65   32646.500000  32646.5  27389  37904   7435.227804

Grouped Values as List:
age
20                         [32601, 21214, 39122]
21                                       [37092]
23                                [30692, 28714]
24                                [37021, 30714]
25                                [24785, 20576]
26           [36691, 29457, 35320, 23520, 21664]
27                                       [33222]
28                                       [22100]
29                         [29091, 30789, 39385]
30                  [26865, 39148, 31950, 38864]
31                                       [33452]
32                         [32283, 26542, 32462]
33                                [29918, 32195]
34                                [23712, 39371]
35                                [33452, 38912]
36                  [23926, 38519, 21191, 37788]
37    [22040, 36656, 28859, 31716, 39543, 34208]
38                                       [28751]
39                                [21239, 28007]
40                  [27773, 22165, 25089, 23181]
41                                [32278, 35312]
42                                       [25617]
43           [21947, 32220, 30195, 37929, 31789]
44                                [34992, 27391]
45                         [26067, 36675, 26830]
46                  [21063, 25015, 22332, 34936]
47                                [25256, 21012]
50                                       [23974]
51                                       [30667]
52                                [38933, 34374]
53                                [28486, 37197]
54                  [32943, 26332, 34357, 27633]
55                         [32322, 20472, 20861]
57                         [20762, 31347, 30736]
58                         [35202, 26798, 32204]
59                                [39369, 30955]
60                                       [36866]
61                                       [31861]
62                                [20494, 27435]
63                                       [38487]
64                         [35397, 35935, 20465]
65                                [37904, 27389]
Name: income, dtype: object

Summary statistics saved to 'summary_statistics.csv'
Grouped values saved to 'grouped_values.csv'